### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by TheIndra55** [TheIndra55/TRAE-menu-hook#4]
- [x] Include binkw32.dll in the zip
- [x] Statically link Minhook.x86.dll so less files are required
- [x] Have `hide_menu_on_start` be true by default, instead show for around 2 seconds we have loaded
- [ ] Allow keys to be changed in the config file
- [x] Map less function keys by default

Maybe even a standalone ASI for only loading mods

**Comment by TheIndra55** [comment]
After statically linking with MinHook linker now yields `MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance` seems non-fatal but should probably check it out.

**Comment by Xan-5** [comment]
> Maybe even a standalone ASI for only loading mods

Yes, please. This would be perfect!

**Comment by TheIndra55** [comment]
Standalone mod loader released at https://github.com/TombRaiderModding/ModLoader.

**Comment by Xan-5** [comment]
Did it last yeat already :) With deficated launcher but you can use dll as ASI too.
https://github.com/Xan-5/TRAmod-TRLmod

**Comment by TheIndra55** [comment]
Improved in #7
